"""Add messages and deliveries

Revision ID: 4dc09dcc1f2a
Revises: b2c4d6e8f0a1
Create Date: 2026-03-23 00:26:09.034201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc09dcc1f2a'
down_revision: Union[str, Sequence[str], None] = 'b2c4d6e8f0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deliveries_id'), 'message_deliveries', ['id'], unique=False)
    op.add_column('messages', sa.Column('encrypted_key', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('message_type', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'message_type')
    op.drop_column('messages', 'encrypted_key')
    op.drop_index(op.f('ix_message_deliveries_id'), table_name='message_deliveries')
    op.drop_table('message_deliveries')
    # ### end Alembic commands ###
